# Jekyll configuration for GitHub Pages
title: "技術ドキュメント集"
description: "各種技術ドキュメントとリファレンス"
baseurl: "/docs"
url: "https://toshi0907.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - jekyll.md
  - git.md
  - nodejs.md
  - python.md
  - nginx.md
  - shellscript.md
  - bat.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages